### ISSUE TITLE
[add software] Add Moulberry/Graphite

### ISSUE THREAD

**Issue by Timongcraft** [GoldenStack/dayssincelastrustmcserver#1]
Source: https://github.com/Moulberry/Graphite
*Release Date* (Initial commit): https://github.com/Moulberry/Graphite/commit/fd9009dba0fe1e157f2285793f57eba5d1f9c423

**Comment by GoldenStack** [comment]
I don't think an initial commit counts as a release date, given it just has a license. I'll probably ask Moulberry if he has an announcement date in mind, but otherwise I'm not sure what commit would "count".

**Comment by GoldenStack** [comment]
A friend found messages by him that make me feel confident enough to say it was announced on 23 June 2022. Thanks for opening the issue
