### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by theorzr** [GoldenStack/dayssincelastrustmcserver#2]
Just asking, is this dedicated to reimplementation of ""latest"" vanilla versions? Because I have an almost complete (+80%) reimplementation of beta 1.7.3 server, if you're interested don't hesitate, my suggestion is not very serious tho. and I love this challenge of reimplementing protocols in Rust in general.

**Comment by GoldenStack** [comment]
I limited it to recent versions as it's basically impossible to make a full implementation because of how much more stuff there is (and implementations of recent versions seem to get more hype either way).

I checked out your project though, and it seems cool! Good luck on it!

**Comment by theorzr** [comment]
Yes I totally understand why you target recent version and I agree on that it's virtually impossible, that's fun tho! 

Thanks for checking it 😄
