### ISSUE TITLE
Missing Entry

### ISSUE THREAD

**Issue by TheMode** [GoldenStack/dayssincelastrustmcserver#4]
Hey awesome project!

I have however noticed the list to be non-exhaustive, especially missing the incredible Minestom project which is in Java but overall still the same as Rust.

Hope you will take my suggestion into account!

**Comment by GoldenStack** [comment]
(for context this is a joke post and I was talking with TheMode on Discord)

Although Minestom is written in Rust, I checked the codebase and it's actually a Roblox server, so I won't add it here.
