### ISSUE TITLE
Another one: "Hyperion"

### ISSUE THREAD

**Issue by admalledd** [GoldenStack/dayssincelastrustmcserver#6]
* https://github.com/andrewgazelka/hyperion
* https://old.reddit.com/r/rust/comments/1fmznnh/hyperion_10k_player_minecraft_game_engine/

**Comment by szostid** [comment]
its already there though

**Comment by admalledd** [comment]
Excuse me, I swear I looked and did a ctrl-f but I am an idiot apparently.
